codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: no
    changes: no

ignore:
  - "com/github/bhop/sparxer/engine/Engine.scala"
  - "com/github/bhop/sparxer/http/HttpServer.scala"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: off